### ISSUE TITLE
Cant send msg using Socket.io

### ISSUE THREAD

**Issue by igorStojanovic0** [igorStojanovic0/sacco_back#13]

**Comment by Joana311** [comment]
could you explain in detail about that

**Comment by igorStojanovic0** [comment]
This also works fine locally, but not so well after deploying to AWS.

**Comment by Joana311** [comment]
did you check nginx configuration

**Comment by igorStojanovic0** [comment]
There is nothing else in the NGINX configuration.

**Comment by Joana311** [comment]
plz share screenshot

**Comment by igorStojanovic0** [comment]
![Uploading Screenshot_2.jpg…]()

**Comment by Joana311** [comment]
plz use useRouter instead window.location

**Comment by igorStojanovic0** [comment]
thank you.
solved
